# Generated by Django 6.1.1 on 2026-09-08 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.CharField(max_length=255, verbose_name='refresh token')),
                ('access_token', models.CharField(blank=True, max_length=255, verbose_name='access token')),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='caduca')),
                ('connected_at', models.DateTimeField(auto_now_add=True, verbose_name='conectado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conexión con Google Calendar',
                'verbose_name_plural': 'conexiones con Google Calendar',
            },
        ),
    ]
