# Generated by Django 6.1.1 on 2026-09-08 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nombre')),
                ('color', models.CharField(default='#2DD4BF', help_text='Hex, ej. #2DD4BF.', max_length=7, verbose_name='color')),
                ('icon', models.CharField(blank=True, help_text='Un emoji, opcional.', max_length=8, verbose_name='icono')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_categories', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='nombre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_tags', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('body', models.TextField(blank=True, verbose_name='contenido')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='fijada')),
                ('reminder_date', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('google_event_id', models.CharField(blank=True, editable=False, max_length=255, verbose_name='id de evento en Google Calendar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última edición')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='notes.category', verbose_name='categoría')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
                ('tags', models.ManyToManyField(blank=True, related_name='notes', to='notes.tag', verbose_name='etiquetas')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=6, verbose_name='prioridad')),
                ('due_date', models.DateField(blank=True, help_text='Si la pones, se sincroniza con tu Google Calendar (si lo tienes conectado) y cuenta como recordatorio.', null=True, verbose_name='fecha límite')),
                ('google_event_id', models.CharField(blank=True, editable=False, max_length=255, verbose_name='id de evento en Google Calendar')),
                ('is_done', models.BooleanField(default=False, verbose_name='hecha')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completada')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última edición')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='notes.category', verbose_name='categoría')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='notes.task', verbose_name='tarea principal')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='notes.tag', verbose_name='etiquetas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'tarea',
                'verbose_name_plural': 'tareas',
                'ordering': ['is_done', 'order', 'due_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='categoria_unica_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='etiqueta_unica_por_usuario'),
        ),
    ]
