# Generated by Django 6.1.1 on 2026-09-08 15:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('category', models.CharField(choices=[('health', '💪 Salud'), ('work', '💼 Trabajo'), ('study', '📚 Estudios'), ('finance', '💰 Finanzas'), ('personal', '🌱 Personal'), ('other', '📌 Otro')], default='other', max_length=10, verbose_name='categoría')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='fecha objetivo')),
                ('is_achieved', models.BooleanField(default=False, verbose_name='conseguido')),
                ('achieved_at', models.DateTimeField(blank=True, null=True, verbose_name='conseguido el')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'objetivo',
                'verbose_name_plural': 'objetivos',
                'ordering': ['is_achieved', 'target_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('is_done', models.BooleanField(default=False, verbose_name='hecho')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='notes.goal')),
            ],
            options={
                'verbose_name': 'paso de objetivo',
                'verbose_name_plural': 'pasos de objetivo',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('is_archived', models.BooleanField(default=False, verbose_name='archivado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to='notes.category', verbose_name='categoría')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'hábito',
                'verbose_name_plural': 'hábitos',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HabitCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='notes.habit')),
            ],
            options={
                'verbose_name': 'marca de hábito',
                'verbose_name_plural': 'marcas de hábito',
                'constraints': [models.UniqueConstraint(fields=('habit', 'date'), name='una_marca_por_habito_y_dia')],
            },
        ),
    ]
