# Generated by Django 6.1.1 on 2026-09-08 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_subject_lecturenote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturenote',
            name='pdf',
            field=models.FileField(blank=True, help_text='Diapositivas o material de la clase, opcional.', null=True, upload_to='uni/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF'),
        ),
    ]
