# Generated by Django 6.1.1 on 2026-09-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_subject_sharing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturenote',
            name='pdf',
        ),
        migrations.AddField(
            model_name='lecturenote',
            name='pdf_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='PDF'),
        ),
        migrations.AddField(
            model_name='lecturenote',
            name='pdf_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='nombre del PDF'),
        ),
    ]
