# Generated by Django 6.1.1 on 2026-09-10 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_remove_lecturenote_pdf_lecturenote_pdf_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('date', models.DateField(verbose_name='fecha')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='hora de inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='hora de fin')),
                ('google_event_id', models.CharField(blank=True, editable=False, max_length=255, verbose_name='id de evento en Google Calendar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última edición')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='notes.category', verbose_name='categoría')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
