# Generated by Django 6.1.1 on 2026-09-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='eliminado el'),
        ),
        migrations.AddField(
            model_name='goal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='eliminado el'),
        ),
        migrations.AddField(
            model_name='habit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='eliminado el'),
        ),
        migrations.AddField(
            model_name='lecturenote',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='eliminado el'),
        ),
        migrations.AddField(
            model_name='note',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='eliminada el'),
        ),
        migrations.AddField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='eliminada el'),
        ),
    ]
